module inflow_interpolation_gpu
  implicit none
contains
  attributes(device) real(8) function cubic_uniform_gpu(y1,y2,y3,y4,x1,delta,xx)
    implicit none
    real(8),value :: y1,y2,y3,y4,x1,delta,xx
    real(8) :: a,b,c,varx,inv_delta

    inv_delta=1.d0/delta
    a=(y4-3.d0*y3+3.d0*y2-y1)*inv_delta**3/6.d0
    b=((y3-2.d0*y2+y1)-6.d0*a*delta**3)*inv_delta**2/2.d0
    c=(y2-y1-a*delta**3-b*delta**2)*inv_delta
    varx=xx-x1
    cubic_uniform_gpu=((a*varx+b)*varx+c)*varx+y1
  end function cubic_uniform_gpu
end module inflow_interpolation_gpu
