module commfunc_gpu

   use cudafor

   implicit none

    contains

   attributes(device) subroutine tridiagonal_thomas_solver_gpu(ac, d, x)
      implicit none
      ! ac(i,1): upper
      ! ac(i,2): diagonal (after preprocessing, e.g. 1/b)
      ! ac(i,3): lower (after preprocessing, e.g. c/b)
      real(8), intent(in)    :: ac(:, :)
      real(8), intent(inout) :: d(:)
      real(8), intent(out)   :: x(size(d))
      integer :: i, n

        n=size(d)

        do i=2,n
            d(i)=d(i)*ac(i,2)-d(i-1)*ac(i,3)
        enddo

        x(n)=d(n)
        do i=n-1,1,-1
            x(i)=d(i)-ac(i,1)*x(i+1)
        enddo

        return
   end subroutine tridiagonal_thomas_solver_gpu

end module commfunc_gpu