#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
COMPARE_DRIVER="$ROOT_DIR/tests/gpu_validation/run_mp3_characteristic_flux_compare.sh"
STAMP="$(date +%Y%m%d_%H%M%S)"
OUT_DIR="${OUT_DIR:-$ROOT_DIR/tests/gpu_validation/out/mp3_characteristic_flux_mpi_$STAMP}"
TOLERANCE_FILE="${TOLERANCE_FILE:-}"
[[ -n "$TOLERANCE_FILE" ]] || { echo "TOLERANCE_FILE is required" >&2; exit 2; }
[[ "$OUT_DIR" == /* ]] || OUT_DIR="$PWD/$OUT_DIR"
[[ "$TOLERANCE_FILE" == /* ]] || TOLERANCE_FILE="$PWD/$TOLERANCE_FILE"
[[ -f "$TOLERANCE_FILE" ]] || { echo "missing tolerance file: $TOLERANCE_FILE" >&2; exit 2; }
[[ ! -e "$OUT_DIR" ]] || { echo "refusing to overwrite MP3 MPI evidence: $OUT_DIR" >&2; exit 2; }

source "$TOLERANCE_FILE"
mkdir -p "$OUT_DIR"

NP=2 TOPOLOGY=2,1,1 GRID=400,8,8 SHOCK_X=0.d0 RANKWISE=f \
  MAXSTEP=3 OUT_DIR="$OUT_DIR/s0a7_x" \
  CANDIDATE_FIELD_ATOL="$CANDIDATE_FIELD_ATOL" \
  CANDIDATE_FIELD_RTOL="$CANDIDATE_FIELD_RTOL" \
  CANDIDATE_STATS_ATOL="$CANDIDATE_STATS_ATOL" \
  CANDIDATE_STATS_RTOL="$CANDIDATE_STATS_RTOL" "$COMPARE_DRIVER"

NP=2 TOPOLOGY=1,2,1 GRID=400,16,8 RANKWISE=t \
  MAXSTEP=3 OUT_DIR="$OUT_DIR/s0a8_y" \
  CANDIDATE_FIELD_ATOL="$CANDIDATE_FIELD_ATOL" \
  CANDIDATE_FIELD_RTOL="$CANDIDATE_FIELD_RTOL" \
  CANDIDATE_STATS_ATOL="$CANDIDATE_STATS_ATOL" \
  CANDIDATE_STATS_RTOL="$CANDIDATE_STATS_RTOL" "$COMPARE_DRIVER"

NP=2 TOPOLOGY=1,1,2 GRID=400,8,16 RANKWISE=t \
  MAXSTEP=3 OUT_DIR="$OUT_DIR/s0a9_z" \
  CANDIDATE_FIELD_ATOL="$CANDIDATE_FIELD_ATOL" \
  CANDIDATE_FIELD_RTOL="$CANDIDATE_FIELD_RTOL" \
  CANDIDATE_STATS_ATOL="$CANDIDATE_STATS_ATOL" \
  CANDIDATE_STATS_RTOL="$CANDIDATE_STATS_RTOL" "$COMPARE_DRIVER"

NP=8 TOPOLOGY=2,2,2 GRID=400,16,16 RANKWISE=t \
  MAXSTEP=3 OUT_DIR="$OUT_DIR/s0a10_2x2x2" \
  CANDIDATE_FIELD_ATOL="$CANDIDATE_FIELD_ATOL" \
  CANDIDATE_FIELD_RTOL="$CANDIDATE_FIELD_RTOL" \
  CANDIDATE_STATS_ATOL="$CANDIDATE_STATS_ATOL" \
  CANDIDATE_STATS_RTOL="$CANDIDATE_STATS_RTOL" "$COMPARE_DRIVER"

echo "MP3 characteristic_flux MPI matrix passed: $OUT_DIR"
